# <NAME:TYPE>
- schema:
    year: INTEGER
    month: INTEGER
    day: INTEGER
    wikimedia_project: STRING
    language: STRING
    title: STRING
    views: INTEGER
  tables:
  # US->EU (multi-regional)
  - source: grey-sort-challenge:src_US_dataset.src_US_table
    destination: grey-sort-challenge:a_EU_dataset.i_was_copied_from_us_to_eu
  # EU->US (multi-regional)
  - source: grey-sort-challenge:src_EU_dataset.src_EU_table
    destination: grey-sort-challenge:a_US_dataset.i_was_copied_from_eu_to_us
  # EU->Tokyo (regional)
  - source: grey-sort-challenge:src_EU_dataset.src_EU_table
    destination: grey-sort-challenge:a_Tokyo_dataset.i_was_copied_from_eu_to_tokyo